cora:
  lr: 0.001
  lr_f: 0.01
  lr_lp: 0.01
  num_hidden: 512 #512
  num_projector_hidden: 256
  num_projector: 256
  num_heads: 4
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  weight_decay_lp: 1e-4
  max_epoch: 2000
  max_epoch_f: 400
  max_epoch_lp: 80
  mask_rate: 0.6 # 0.6
  temperature: 1
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.1
  attn_drop: 0.1
  linear_prob: True
  scheduler: True
  loss_fn: sce
  loss_weight: 0.3 # 0.5
  augmentation: drop_node # evc
  drop_node_rate: 0.5
  drop_edge_rate: 0.3
  drop_feature_rate: 0.3
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  mu: 0.3 # 0.3
  nu: 0.5 # 0.5
citeseer:
  lr: 0.001
  lr_f: 0.01
  lr_lp: 0.01
  num_hidden: 1024 # 1024
  num_projector_hidden: 512 # 512
  num_projector: 512 # 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_f: 1e-4
  weight_decay_lp: 0.01
  max_epoch: 2000
  max_epoch_f: 400
  max_epoch_lp: 100
  mask_rate: 0.7 #0.75
  temperature: 0.4 # 0.1
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.1
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  loss_weight: 0.3 # 0.3
  augmentation:  drop_node #pr
  drop_node_rate: 0.7
  drop_edge_rate: 0.5
  drop_feature_rate: 0.2
  alpha_l: 1 # or 3
  scheduler: True
  mu: 0.5 # 0.5
  nu: 0.7  #0.7
pubmed:
  lr: 0.001
  lr_f: 0.01
  lr_lp: 0.01
  num_hidden: 512 # 512
  num_projector_hidden: 512
  num_projector: 256
  num_heads: 4
  num_layers: 6
  weight_decay: 1e-5
  weight_decay_f: 1e-4
  weight_decay_lp: 1e-4
  max_epoch: 1500
  max_epoch_f: 300
  max_epoch_lp: 50
  mask_rate: 0.8
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.05
  alpha_l: 3
  temperature: 0.6
  loss_weight: 0.6
  augmentation: drop_node
  drop_node_rate: 0.5
  drop_edge_rate: 0.6
  drop_feature_rate: 0.4
  scheduler: True
  mu: 0.2
  nu: 0.3
reddit:
  lr: 0.001
  lr_f: 0.005
  num_hidden: 512
  num_heads: 2
  weight_decay: 2e-4
  weight_decay_f: 0
  max_epoch: 500
  max_epoch_f: 500
  mask_rate: 0.75
  num_layers: 4
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.15
  drop_edge_rate: 0.5
  alpha_l: 3
  norm: layernorm
  residual: True
  scheduler: True
  linear_prob: True
IMDB-BINARY:
  lr: 0.00015
  deg4feat: True
  num_hidden: 512
  num_heads: 2
  weight_decay: 1e-6
  max_epoch: 100
  mask_rate: 0.6
  num_layers: 2
  encoder: gin
  decoder: gin
  activation: prelu
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  norm: batchnorm
  residual: False
  scheduler: False
  pooling: mean
  batch_size: 8
  alpha_l: 1
  loss_weight: 0.6
  num_projector_hidden: 512
  num_projector: 512
  temperature: 1.0
  augmentation: drop_node
  drop_node_rate: 0.4
  nu: 0.8
IMDB-MULTI:
  lr: 0.00015
  num_hidden: 1024
  num_projector_hidden: 512
  num_projector: 512
  num_heads: 2
  weight_decay: 2e-5
  max_epoch: 100
  mask_rate: 0.7
  num_layers: 2
  encoder: gin
  decoder: gin
  activation: prelu
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  loss_weight: 0.5
  norm: batchnorm
  scheduler: False
  linear_prob: True
  pooling: mean
  batch_size: 32
  alpha_l: 3
  temperature: 0.5
  augmentation: drop_edge
  drop_node_rate: 0.2
  drop_edge_rate: 0.4
  drop_feature_rate: 0.6
  nu: 1.0
MUTAG:
  num_hidden: 32
  num_layers: 5
  lr: 0.0005
  weight_decay: 0.00
  mask_rate: 0.75
  max_epoch: 10
  encoder: gin
  decoder: gin
  activation: prelu
  loss_fn: sce
  scheduler: False  
  pooling: sum
  batch_size: 64
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  in_drop: 0.2
  attn_drop: 0.1
  num_projector_hidden: 64
  num_projector: 32
  temperature: 0.4
  loss_weight: 0.5
  augmentation: pr
  drop_edge_rate: 0.8
  drop_feature_rate: 0.8

REDDIT-BINARY:
  lr: 0.00015
  weight_decay: 0.0
  max_epoch: 100
  mask_rate: 0.75
  num_hidden: 1024
  num_layers: 2
  encoder: gin
  decoder: gin
  activation: prelu
  pooling: sum
  scheduler: True
  batch_size: 8
  replace_rate: 0.1
  norm: layernorm
  loss_fn: sce
  alpha_l: 2
  num_projector_hidden: 512
  num_projector: 512
  temperature: 0.5
  loss_weight: 1
  augmentation: drop_node
  drop_node_rate: 0.5
  drop_edge_rate: 0.2
  drop_feature_rate: 0.6
COLLAB:
  lr: 0.00015
  weight_decay: 0.0
  max_epoch: 20
  num_layers: 2
  num_hidden: 256
  mask_rate: 0.75
  activation: relu
  encoder: gin
  decoder: gin
  scheduler: True
  pooling: max
  batch_size: 32
  loss_fn: sce
  norm: batchnorm
  alpha_l: 1
  augmentation: drop_node
  drop_node_rate: 0.2
  drop_edge_rate: 0.2
  drop_feature_rate: 0.4
NCI1:
  lr: 0.001
  max_epoch: 300
  num_layers: 2
  num_hidden: 512
  mask_rate: 0.25 # not 0.75
  drop_edge_rate: 0.0
  activation: prelu
  encoder: gin
  decoder: gin
  scheduler: True
  pool: sum
  batch_size: 16
  alpha_l: 2
  replace_rate: 0.1
  norm: batchnorm
  loss_fn: sce
