cora:
  lr: 0.001
  lr_lp: 0.01
  num_hidden: 512
  num_projector_hidden: 512
  num_projector: 512
  num_heads: 4
  weight_decay: 2e-4
  max_epoch: 1
  mask_rate: 0.5
  temperature: 0.6
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  loss_fn: sce
  loss_weight: 0.2
  augmentation: drop_node
  drop_node_rate: 0.2
  drop_edge_rate: 0.4
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 2
  scheduler: True
  mu: 0.9
  nu: 0.3
citeseer:
  lr: 0.001
  num_hidden: 512
  num_projector_hidden: 1024
  num_projector: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  max_epoch: 1500
  mask_rate: 0.6
  temperature: 0.1
  encoder: gat
  decoder: gat
  activation: relu
  in_drop: 0.2
  attn_drop: 0.1
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.1
  loss_weight: 0.1
  drop_node_rate: 0.8
  alpha_l: 3 # or 3
  scheduler: True
  mu: 0.7
  nu: 0.1
pubmed:
  lr: 0.001
  num_hidden: 2048
  num_projector_hidden: 1024
  num_projector: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  max_epoch: 1000
  mask_rate: 0.5
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 3
  temperature: 0.3
  loss_weight: 0.8
  augmentation: drop_node
  drop_node_rate: 0.5
  scheduler: True
  mu: 0.7
  nu: 0.4