cora:
  lr: 0.001
  lr_lp: 0.01
  num_hidden: 512
  num_projector_hidden: 256
  num_projector: 256
  num_heads: 4
  weight_decay: 2e-5
  weight_decay_lp: 1e-4
  max_epoch: 1000
  max_epoch_lp: 500
  mask_rate: 0.3 # 0.6
  temperature: 0.7
  num_layers: 2
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.1
  attn_drop: 0.3
  scheduler: True
  loss_fn: sce
  loss_weight: 0.4
  augmentation: drop_node
  drop_node_rate: 0.7
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 2
  mu: 1
  nu: 0.2
citeseer:
  lr: 0.001
  lr_lp: 0.01
  num_hidden: 2048
  num_projector_hidden: 1024
  num_projector: 512
  num_heads: 2
  num_layers: 2
  weight_decay: 2e-5
  weight_decay_lp: 0.01
  max_epoch: 2000
  max_epoch_lp: 700
  mask_rate: 0.5
  temperature: 0.3
  encoder: gat
  decoder: gat
  activation: prelu
  in_drop: 0.5
  attn_drop: 0.3
  linear_prob: True
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  loss_weight: 0.8
  augmentation:  drop_node
  drop_node_rate: 0.5
  alpha_l: 3
  scheduler: True
  mu: 0.6
  nu: 0.2 
pubmed:
  lr: 0.001
  lr_lp: 0.01
  num_hidden: 1024
  num_projector_hidden: 512
  num_projector: 512
  num_heads: 4
  num_layers: 2
  weight_decay: 1e-5
  weight_decay_lp: 1e-4
  max_epoch: 1500
  max_epoch_lp: 300
  mask_rate: 0.4
  encoder: gin
  decoder: gin
  activation: prelu
  in_drop: 0.4
  attn_drop: 0.4
  loss_fn: sce
  optimizer: adam
  replace_rate: 0.0
  alpha_l: 4
  temperature: 0.6
  loss_weight: 0.5
  augmentation: drop_node
  drop_node_rate: 0.9
  scheduler: True
  mu: 0.9
  nu: 1.0


